"""add a used column to Trivia

Revision ID: 82c83a80fab1
Revises: d6be8b9fd22d
Create Date: 2024-03-25 20:21:48.057374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c83a80fab1'
down_revision: Union[str, None] = 'd6be8b9fd22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('used', sa.Boolean(), nullable=False, server_default=str(False)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia', 'used')
    # ### end Alembic commands ###
