"""Change Trivia used to Date from Bool and add TrivaStat

Revision ID: bc1a4d27619b
Revises: 82c83a80fab1
Create Date: 2024-04-05 15:28:15.418878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from BanishedBot.utils import Json

# revision identifiers, used by Alembic.
revision: str = 'bc1a4d27619b'
down_revision: Union[str, None] = '82c83a80fab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia_stat',
    sa.Column('question_id', sa.Unicode(length=24), nullable=False),
    sa.Column('correct_answer', Json(), server_default="[]", nullable=False),
    sa.Column('incorrect_answer', Json(), server_default="[]", nullable=False),
    sa.Column('no_answer', Json(), server_default="[]", nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['trivia.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.drop_column('trivia', 'used')
    op.add_column('trivia', sa.Column('used', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia', 'used')
    op.add_column('trivia', sa.Column('used', sa.Boolean(), server_default=False, nullable=False))
    op.drop_table('trivia_stat')
    # ### end Alembic commands ###
