"""event start and end to datetime

Revision ID: fded1f1a6b6c
Revises: 6bc27e66166d
Create Date: 2024-05-10 16:06:10.726152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fded1f1a6b6c'
down_revision: Union[str, None] = '6bc27e66166d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_time')
    op.add_column('events', sa.Column('start_time', sa.DateTime, nullable=True))
    op.drop_column('events', 'end_time')
    op.add_column('events', sa.Column('end_time', sa.DateTime, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_time')
    op.add_column('events', sa.Column('start_time', sa.DATE, nullable=True))
    op.drop_column('events', 'end_time')
    op.add_column('events', sa.Column('end_time', sa.DATE, nullable=True))
    # ### end Alembic commands ###
